import { tintInPlace } from './tint'

// Small greyscale thumbnails of each figure, generated by the build from the
// sliced parts. Reading them here keeps Rule 3 intact — figure assets are
// only ever touched inside src/figure/.
//
// The figure-select screen uses these instead of loading a full adapter per
// figure: ten adapters would mean 140 decoded full-size bitmaps, which is
// enough to exhaust a phone's memory before the child has drawn anything.

const previewUrls = import.meta.glob('../packs/*/previews/*.png', {
  eager: true, query: '?url', import: 'default'
}) as Record<string, string>

function previewUrl(figureId: string): string | null {
  const entry = Object.entries(previewUrls).find(([p]) => p.endsWith(`/previews/${figureId}.png`))
  return entry ? entry[1] : null
}

const cache = new Map<string, Promise<HTMLImageElement | null>>()

function loadPreview(figureId: string): Promise<HTMLImageElement | null> {
  let p = cache.get(figureId)
  if (!p) {
    const url = previewUrl(figureId)
    p = url
      ? new Promise<HTMLImageElement | null>((resolve) => {
          const img = new Image()
          img.onload = () => resolve(img)
          img.onerror = () => resolve(null)
          img.src = url
        })
      : Promise.resolve(null)
    cache.set(figureId, p)
  }
  return p
}

/** Draw a figure thumbnail in the given skin tone, optionally mirrored. */
export async function renderFigurePreview(
  canvas: HTMLCanvasElement,
  figureId: string,
  tone: string,
  mirrored: boolean
): Promise<void> {
  const img = await loadPreview(figureId)
  const ctx = canvas.getContext('2d')
  if (!ctx) return
  ctx.clearRect(0, 0, canvas.width, canvas.height)
  if (!img) return

  // Tint on a private canvas so the shared scratch buffers stay untouched by
  // the caller's own drawing.
  const shaded = document.createElement('canvas')
  shaded.width = canvas.width
  shaded.height = canvas.height
  const shadedCtx = shaded.getContext('2d')!
  shadedCtx.drawImage(img, 0, 0, shaded.width, shaded.height)
  tintInPlace(shaded, tone)

  ctx.save()
  if (mirrored) {
    ctx.translate(canvas.width, 0)
    ctx.scale(-1, 1)
  }
  ctx.drawImage(shaded, 0, 0)
  ctx.restore()
}
